apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: "1.25.1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/version: "1.25.1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/version: "1.25.1"
    spec:
      containers:
      - name: nginx
        image: nginx::1.25.4
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 1Gi
            cpu: 0.25
      nodeSelector: 
        kubernetes.io/hostname: lab-worker3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/deployment: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: nginx
spec:
  ingressClassName: "nginx"
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ngixn
                port: 
                  number: 443
